TOP	= ../../..
include ${TOP}/make/makefile.common

SRC = fifo.v            \
      clkgen.sv         \
      fifo_if.sv        \
      fifo_env.sv       \
      fifo_pkg.sv       \
      tb_pkg.sv         \
      top.sv
