TOP	= ../../..
include ${TOP}/make/makefile.common

SV_SRC	= fifo.sv           \
	  clkgen.sv         \
	  fifo_if.sv        \
	  fifo_env.sv       \
	  fifo_pkg.sv       \
	  tb_pkg.sv         \
	  top.sv

C_SRC	= main.cpp

SRC	= ${SV_SRC} ${C_SRC}
