TOP	= ../../..
include ${TOP}/make/makefile.common

SRC =  ../block_tb/block_dut.v                    \
       ../block_tb/block_dut_env.sv               \
       ../block_tb/block_tb_pkg.sv                \
       ../multi_if_tb/multi_if_dut.v              \
       ../multi_if_tb/multi_if_dut_env.sv         \
       ../multi_if_tb/multi_if_pkg.sv             \
       system_dut_env.sv                          \
       system_tb_pkg.sv                           \
       test_pkg.sv                                \
       top.sv

INC	+= +incdir+../block_tb +incdir+../multi_if_tb
