TOP	= ../../..
include ${TOP}/make/makefile.common

SRC =  multi_if_dut.v              \
       multi_if_dut_env.sv         \
       ../block_tb/block_tb_pkg.sv \
       multi_if_pkg.sv             \
       test_pkg.sv                 \
       top.sv

INC	+= +incdir+../block_tb
