#-------------------------------------------------------------------------------
# makefile
#-------------------------------------------------------------------------------

TOP	= ..
include ${TOP}/make/tools.mk

all: doc

build : doc

doc :
	${DOXYGEN} Doxyfile

run :

clean :
	rm -rf html

