TOP	= ../../../..
include ${TOP}/make/makefile.common

SV_SRC =  	block_dut.v      \
                block_dut_env.sv \
                sync_if.sv       \
                block_binds.sv   \
                block_tb_pkg.sv  \
                test_pkg.sv      \
                top.sv

C_SRC	= 	main.cpp

SRC	= 	${SV_SRC} ${C_SRC}
