
TOP	= ../../..
include ${TOP}/make/makefile.common

INC	+= +incdir+../abstract_factory                \
           +incdir+../type_handle_1/
SRC	= ../type_handle_1/type_handle_pkg.sv         \
          ../abstract_factory/abstract_factory_pkg.sv \
          type_factory_pkg.sv                         \
          class_family_pkg.sv                         \
          top.sv

