
TOP	= ../../..
include ${TOP}/make/makefile.common

INC	+= +incdir+../abstract_factory
SRC	= ../abstract_factory/abstract_factory_pkg.sv \
          type_factory_pkg.sv                         \
          class_family_pkg.sv                         \
          top.sv

